name: preprocess-img
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.2.2
  - pandas=2.2.3
  - matplotlib
  - scikit-image
  - pillow=11.1.0
  - tifffile=2025.1.10
  - plotly=5.24.1
  - ipykernel=6.25.1
  - packaging=24.2
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - tzdata
  - six=1.17.0
  - tenacity=9.0.0
  - paramiko=3.2.0
  - nbformat>=4.2.0
  - openpyxl
  - pip
  - pip:
      - bioio-ome-zarr
      - bioio-nd2
      - pybdv
      - imaris_ims_file_reader
      - patchify
      - aicspylibczi
